############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About Us"
url = "/about"
weight = 2


[[main]]
weight = 4
name = "Services"

[[main]]
parent = "Services"
name = "Blog"
url = "/blog"

[[main]]
parent = "Services"
name = "Contact"
url = "/contact"

[[main]]
parent = "Services"
name = "Authors"
url = "/authors"

[[main]]
parent = "Services"
name = "Categories"
url = "/categories"

[[main]]
parent = "Services"
name = "404 Page"
url = "/404"

[[main]]
parent = "Services"
name = "Comment Policy"
url = "/comment-policy"

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Contact Us"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
